// packages/svelte-ui/src/Button.svelte
<script lang="ts">
  export let variant: 'primary' | 'secondary' = 'primary';

  const base = {
    borderRadius: '6px',
    padding: '8px 12px',
    fontSize: '14px',
    cursor: 'pointer',
    border: '1px solid transparent',
  } as const;

  const theme = {
    primary: { background: '#111827', color: 'white' },
    secondary: { background: '#F3F4F6', color: '#111827', borderColor: '#D1D5DB' },
  } as const;

  $: style = { ...base, ...theme[variant] };
</script>

<button style={style}><slot /></button>

// packages/react-ui/src/Button.tsx
import * as React from 'react';

export type ButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement> & {
  variant?: 'primary' | 'secondary';
};

export function Button({ variant = 'primary', style, children, ...rest }: ButtonProps) {
  const base: React.CSSProperties = {
    borderRadius: 6,
    padding: '8px 12px',
    fontSize: 14,
    cursor: 'pointer',
    border: '1px solid transparent',
  };
  const theme: Record<string, React.CSSProperties> = {
    primary: { background: '#111827', color: 'white' },
    secondary: { background: '#F3F4F6', color: '#111827', borderColor: '#D1D5DB' },
  };
  return (
    <button style={{ ...base, ...theme[variant], ...style }} {...rest}>
      {children}
    </button>
  );
}
